# This workflow builds and deploys the documentation when there is a push event to either the main or dev branch
name: Documentation

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
  
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          cd docs
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build Sphinx Documentation
        run: |
          cd docs
          make html

      - name: Deploy Sphinx Documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
