name: Publish to PyPI

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  id-token: write
  contents: read

jobs:
  build-and-publish:
    name: Publish package to PyPI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    environment:
      name: PyPi

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tool
        run: pip install build cibuildwheel

      # Only build source on one platform (e.g., Linux)
      - name: Build sdist
        if: matrix.os == 'ubuntu-latest'
        run: python -m build --sdist --outdir dist

      - name: Build wheels
        env:
          CIBW_BUILD: "cp310-* cp311-* cp312-*"
        run: |
          cibuildwheel --output-dir dist

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}
          path: dist/

  publish:
    name: Publish to PyPI
    needs: build-and-publish
    runs-on: ubuntu-latest
    environment:
      name: PyPi

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: dist-*
          merge-multiple: true
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist