name: Publish to PyPI

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    name: Publish package to PyPI
    runs-on: ubuntu-latest
    environment:
      name: PyPi

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tool
        run: pip install build cibuildwheel

      - name: Build sdist
        run: python -m build --sdist --outdir dist

      - name: Build wheels
        run: |
          cibuildwheel --output-dir dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
